language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies

install:
  - pip install pipenv codecov --upgrade
  - pipenv install --dev

script:
  - pytest --cov=./
  - codecov --token=$CODECOV_TOKEN
