language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies

install:
  - pip install pipenv --upgrade
  - pipenv install

script:
  - pytest
